### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by ghost** [yubaoquan/auto-close-html2#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Unknown Windows version
**Thrown From**: [auto-close-html2](https://github.com/yubaoquan/auto-close-html2) package 0.7.0

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\Matteo\.atom\packages\auto-close-html2\lib\auto-close-html2.js:145

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    at /packages/auto-close-html2/lib/auto-close-html2.js:105:18
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.28.0/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.28.0/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.28.0/resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.28.0/resources/app/src/pane.js:444:48)
    at Pane.activateItem (~/AppData/Local/atom/app-1.28.0/resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/tabs/lib/tab-bar-view.js:730:25)
```

### Commands

```
     -6:00.7.0 core:save (input.hidden-input)
     -4:22.4.0 core:paste (input.hidden-input)
     -4:09.8.0 core:backspace (input.hidden-input)
     -4:05.7.0 core:save (input.hidden-input)
     -3:57.3.0 core:backspace (input.hidden-input)
  2x -3:56.4.0 core:save (input.hidden-input)
     -2:49.1.0 core:backspace (input.hidden-input)
     -2:48.3.0 core:save (input.hidden-input)
  7x -2:13.8.0 core:backspace (input.hidden-input)
     -2:04.4.0 autocomplete-plus:confirm (input.hidden-input)
     -2:01.2.0 core:save (input.hidden-input)
  3x -1:47.7.0 core:backspace (input.hidden-input)
  2x -1:45.3.0 core:save (input.hidden-input)
     -1:05.5.0 core:confirm (input.hidden-input)
  2x -0:50 core:backspace (input.hidden-input)
     -0:43.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-clock 0.1.16 
atom-i18n 0.15.0 
atom-ide-ui 0.12.0 
atom-wrap-in-tag 0.6.0 
auto-close-html2 0.7.0 
color-picker 2.3.0 
data-atom 0.29.0 
double-tag 1.5.0 
emmet 2.4.3 
file-icons 2.1.21 
highlight-selected 0.13.1 
ide-php 0.7.14 
ide-typescript 0.7.6 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
v-bootstrap4 0.2.2 
```

**Comment by javaskript** [comment]
My changes in https://github.com/yubaoquan/auto-close-html2/pull/6/commits/412b25f4e7a49473d419fabb729f7462ea8adc4d have fixed this bug.
