### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by sandysekhon** [yubaoquan/auto-close-html2#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [auto-close-html2](https://github.com/yubaoquan/auto-close-html2) package 0.7.0

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/sundeepsekhon/.atom/packages/auto-close-html2/lib/auto-close-html2.js:145

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    at /packages/auto-close-html2/lib/auto-close-html2.js:105:18
    at Function.simpleDispatch (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1173795)
    at Workspace.didActivatePaneContainer (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:424001)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:468782)
    at Function.simpleDispatch (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1172354)
    at Emitter.emit (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1173795)
    at PaneContainer.didActivatePane (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:446187)
    at Pane.activate (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:463516)
    at Pane.focus (/private/var/folders/6_/617xlf4x0d9bv4n0kbs_dcw40000gp/T/AppTranslocation/A7E67DAE-F054-45B1-B1FE-94856A4F5371/d/Atom.app/Contents/Resources/app/static/<embedded>:11:454969)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -7:46.9.0 core:save (input.hidden-input)
  2x -7:42.5.0 core:move-left (input.hidden-input)
     -7:41.3.0 core:save (input.hidden-input)
     -1:27.5.0 application:new-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:23.8.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -1:02.8.0 tree-view:move (span.name.icon.icon-file-text)
     -0:54.8.0 core:confirm (input.hidden-input)
  2x -0:50.2.0 core:backspace (input.hidden-input)
     -0:26.7.0 tree-view:move (span.name.icon.icon-file-text)
     -0:26.4.0 core:move-right (input.hidden-input)
  5x -0:26 core:move-left (input.hidden-input)
     -0:25.2.0 core:backspace (input.hidden-input)
  4x -0:25 core:move-left (input.hidden-input)
     -0:24.3.0 core:move-right (input.hidden-input)
     -0:24.1.0 core:backspace (input.hidden-input)
     -0:23.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
auto-close-html2 0.7.0 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
prettier-atom 0.56.4 
```

**Comment by m1ga** [comment]
https://github.com/yubaoquan/auto-close-html2/pull/6 fixes this issue

**Comment by YogiOneKanobi** [comment]
+1 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [auto-close-html2](https://github.com/yubaoquan/auto-close-html2) package 0.7.0


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/itech/.atom/packages/auto-close-html2/lib/auto-close-html2.js:145

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    at /packages/auto-close-html2/lib/auto-close-html2.js:105:18
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:424073)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:468898)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446309)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:463632)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455075)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -0:26.6.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:11 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-clean 2.24.1 
atom-css-comb 3.5.1 
atom-live-server 2.3.0 
auto-close-html2 0.7.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-font-awesome 1.0.2 
autocomplete-html-entities 0.2.0 
autocomplete-modules 2.3.0 
busy-signal 2.0.1 
close-tags 0.6.0 
color-picker 2.3.0 
css-snippets 1.1.0 
file-icons 2.1.34 
ftp-remote-edit 0.17.2 
git-plus 8.7.1 
highlight-selected 0.16.0 
intentions 1.1.5 
linter 2.3.1 
linter-csslint 2.0.6 
linter-htmlhint 1.6.2 
linter-ui-default 1.7.1 
monokai-seti 0.9.0 
pigments 0.40.2 
project-manager 3.3.7 
seti-syntax 1.2.0 
seti-ui 1.11.0 
```

**Comment by solodmd** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [auto-close-html2](https://github.com/yubaoquan/auto-close-html2) package 0.7.0


### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At /Users/dengmingdi/.atom/packages/auto-close-html2/lib/auto-close-html2.js:145

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/auto-close-html2/lib/auto-close-html2.js:145:25)
    at /packages/auto-close-html2/lib/auto-close-html2.js:105:18
    at Function.simpleDispatch (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Workspace.didActivatePaneContainer (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:424073)
    at WorkspaceCenter.paneContainer.onDidActivatePane (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:14:44249)
    at Function.simpleDispatch (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at PaneContainer.didActivatePane (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:446309)
    at Pane.activate (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:463632)
    at Pane.focus (/private/var/folders/49/_rm8lgf93sxd8sfhd_kq9n1w0000gn/T/AppTranslocation/72D00009-8177-4075-86FE-91DDFC1B12E3/d/Atom.app/Contents/Resources/app/static/<embedded>:11:455075)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-ternjs 0.20.0 
auto-close-html2 0.7.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
docblockr 0.13.7 
duplicate-line-or-selection 0.9.0 
element-helper 0.5.4 
emmet 2.4.3 
git-log 0.4.1 
git-plus 8.7.1 
goto-definition 1.3.4 
hyperclick 0.1.5 
intentions 1.1.5 
language-eml 1.2.5 
language-vue 0.25.0 
linter 2.3.1 
linter-jshint 3.1.16 
linter-ui-default 1.8.0 
minimap 4.29.9 
open-in-browser 0.5.2 
platformio-ide-terminal 2.9.4 
project-manager 3.3.7 
sublime-block-comment 0.5.1 
vim-mode 0.66.0 
```

**Comment by m1ga** [comment]
@solodmd https://github.com/yubaoquan/auto-close-html2/issues/8#issuecomment-496013976
